# Setup
title:            ByeMC
tagline:          'A guy who blogs'
description:      'Hello. You came from somewhere... but... lets face it. I don&#39;t care.'
url:              https://byemc.xyz
baseurl:          '/hyde'
paginate:         5

# About and contact
author:
  name:           'ByeMC'
  url:            https://twitter.com/_byemc

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          'not caring'
